### ISSUE TITLE
[instant-revive] hook: Error: obsolete definition (S_PARTY_MEMBER_LIST.7)

### ISSUE THREAD

**Issue by Loliconera** [Lambda11/instant-revive#5]
```
[17:51:48.238] [mods] ERROR: El modulo "Instant-Revive" (instant-revive) no pudo aplicar su componente de red al servidor!
[17:51:48.238] [mods] ERROR: Contactate con el autor del modulo:: https://github.com/Lambda11/instant-revive/issues
[17:51:48.238] Error: [dispatch] [instant-revive] hook: Error: obsolete definition (S_PARTY_MEMBER_LIST.7)
    at Dispatch.createHook (C:\Users\Usuario\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:230:27)
    at Dispatch.hook (C:\Users\Usuario\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch.js:265:27)
    at Proxy.hook (C:\Users\Usuario\AppData\Local\Programs\TeraToolbox\bin\mod.js:280:36)
    at new Instant_revive (C:\Users\Usuario\AppData\Local\Programs\TeraToolbox\mods\instant-revive-master\index.js:55:6)
    at new <anonymous> (C:\Users\Usuario\AppData\Local\Programs\TeraToolbox\bin\mod-legacy-wrapper.js:144:13)
    at Mod.loadNetworkInstance (C:\Users\Usuario\AppData\Local\Programs\TeraToolbox\bin\mod.js:595:31)
    at ModManager.loadNetwork (C:\Users\Usuario\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:252:20)
    at C:\Users\Usuario\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:233:22
    at Map.forEach (<anonymous>)
    at ModManager.loadAllNetwork (C:\Users\Usuario\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:231:25)
```

**Comment by ChicknWing** [comment]
I forked the mod and fixed it.

**Comment by Lambda11** [comment]
should be fixed now here as well
